
package scanner;

public enum Token {
    COMENTARIO, IDENTIFICADOR, LITERAL, PALABRA_RESERVADA,ERROR,VERBO,PRONOMBRE,SUSTANTIVO, SIGNO
  , ADVERBIO, ADJETIVO, PREPOSICION, ARTICULO, LITERALES, NOMBRE_PROPIO, SIGNO_PREGUNTA_ABRE,SIGNO_PREGUNTA_CIERRA, COMA, PUNTO
}
